import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import axios from "axios";
const api = "https://fakestoreapi.com/products"

const initialState = {
  products: []
}

// This where async logic goes
export const fetchProducts = createAsyncThunk(
  "products/fetchProducts",
  async () => {
    const response = await axios.get(api)
    const data = response.data
    return data
  }
)

export const productsSlice = createSlice ({
  name:"products",
  initialState,
  // The 'reducers' field lets us define reducers and generate associated actions
  // This is where direct logic goes.
  reducers: {

  },
  // The 'extraReducers' field lets the slice handle actions defined elswhere
  // including actions generated by createAsyncThunk or in other slices

  // This where async logic goes
  extraReducers: (builder) => {
    builder
      .addCase(fetchProducts.fulfilled, (state, action) => {
        state.products = action.payload;
      })
      .addCase(fetchProducts.rejected, (state, action) => {
        state.products = []
      })
  }
})

export default productsSlice.reducer